name: Allure Integration

on: [push]

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Cypress run with Cucumber
        run: |
          npm install
          npm run cypress:execution-allure

      - name: Get Allure history
        uses: actions/checkout@v2
        if: always()
        continue-on-error: true
        with:
          ref: allure
          path: allure

      - name: Copy Allure history
        run: |
          mkdir -p allure-results/history
          ls -al allure/last-history # Ajout de cette ligne pour déboguer
          cp -R allure/last-history/* allure-results/history || true

      - name: Generate Allure Report
        uses: simple-elf/allure-report-action@master
        if: always()

      - name: Deploy report to Github Pages
        if: always()
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: allure
          publish_dir: allure-history
          user_name: 'GitHub Actions'
          user_email: 'actions@github.com'
          commit_message: 'Deploy Allure report to allure branch'
