name: Allure Integration

on:
  push:
    branches:
      - main

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Cypress run with Cucumber
        uses: cypress-io/github-action@v4.2.0
        with:
          command: npm run cypress:execution-allure

      - name: Copy Allure history
        run: |
          mkdir -p allure-results/history
          cp -R gh-pages/last-history/* allure-results/history || true

      - name: Generate Allure Report
        uses: simple-elf/allure-report-action@master
        with:
          allure_results: allure-results
          gh_pages: allure

      - name: Deploy report to Github Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: allure
          publish_dir: allure-history
          user_name: 'GitHub Actions'
          user_email: 'actions@github.com'
          commit_message: 'Deploy Allure report to allure branch'
