name: Allure Integration

on:
  push:
    branches:
      - main  # Vous pouvez ajuster cette branche en fonction de votre configuration

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 14

      - name: Install Dependencies
        run: npm install

      - name: Cypress run with Cucumber and Allure
        run: npm run cypress:execution-allure

      - name: Get Allure history
        uses: actions/checkout@v2
        if: always()
        continue-on-error: true
        with:
          ref: allure
          path: allure

      - name: Generate Allure Report
        uses: simple-elf/allure-report-action@master
        if: always()

      - name: Deploy report to GitHub Pages
        if: always()
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: allure
          publish_dir: allure-history
          user_name: 'GitHub Actions'
          user_email: 'actions@github.com'
          commit_message: 'Deploy Allure report to allure branch'
